name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        id: configure-pages
        uses: actions/configure-pages@v5
    
      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-pages-artifact@v3
        with:
            path: "."

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deploy-to-github-pages.outputs.page_url}}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v4
